### Installing all the pakages 

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\prava\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [2]:
!pip install pandas


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\prava\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [3]:
!pip install scikit-learn


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\prava\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


### Importing Packages

In [4]:
import pandas as pd
import numpy as np


In [5]:
from sklearn.impute import SimpleImputer

In [6]:
from sklearn.compose import ColumnTransformer

### imporing Datasets

In [7]:
dataset = pd.read_csv(r'C:\Users\prava\100_days_of _ML\datasets\Data.csv')

In [8]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
X= dataset.iloc[:,:-1].values
Y= dataset.iloc[:,3].values

In [10]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [11]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

### Handling Missing values

In [12]:
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
X[:,1:3] = imputer.fit_transform(X[:,1:3])

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### Ecoding Categorical Data

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [15]:
labelencoder_X= LabelEncoder()

In [16]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [17]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

### Checking Dummy Variable

In [18]:
column_transformer = ColumnTransformer(
    [('one_hot_encoder',OneHotEncoder(),[0])],remainder = 'passthrough'
)

In [19]:
X= column_transformer.fit_transform(X)

In [20]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [21]:
labelencoder_y=LabelEncoder()

In [22]:
Y= labelencoder_y.fit_transform(Y)

In [23]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Splitting the dataset into traning and testing sets

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.3, random_state = 0)

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc_X= StandardScaler()

In [28]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

## Chose a Machine Learning Model 

There are two types of models 
#### 1 Classification
(Predicting the categories of values liek "Spam"/"Not Spam", "True"/"False")
Eg: Logistic Regression, Random Forest , SVM

#### 2 Regression 
(Predits the contious values like what can be the price or salary after few years depending on the current factors for the saeme postions/ what can be projection of house value in future)
eg: Linear Regression, decision Trees etc

##### Now i am using Logistic Regression to classify my data 

### Import and train the model

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
classifier = LogisticRegression()

In [31]:
classifier.fit(X_train,Y_train)

LogisticRegression()

### Make predictions

In [32]:
Y_pred = classifier.predict(X_test)


### Evaluate performance

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy =  accuracy_score(Y_test,Y_pred)

In [35]:
accuracy

0.6666666666666666

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
cm = confusion_matrix(Y_test, Y_pred)

In [38]:
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[1 1]
 [0 1]]


In [39]:
from sklearn.metrics import classification_report

In [40]:
print("Classification Report:\n", classification_report(Y_test, Y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3



In [41]:
# Count occurrences of each class
unique, counts = np.unique(Y_train, return_counts=True)
print("Training set class distribution:", dict(zip(unique, counts)))

unique, counts = np.unique(Y_test, return_counts=True)
print("Test set class distribution:", dict(zip(unique, counts)))


Training set class distribution: {0: 3, 1: 4}
Test set class distribution: {0: 2, 1: 1}


#### Since the dataset is very small, the model tends to predict more for class 0 and less for class 1.

#### It's day 1 of my machine learning journey from scratch, and today I've started by diving into the basics. I plan to focus on one example of each algorithm and learn them in detail as I progress.